[build.environment]
  NPM_FLAGS = "--prefix=/dev/null --force"
  NODE_VERSION = "16.11.1"
  NPM_VERSION = "6.14.15" # Required because NPM_FLAGS fail on newer versions

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"